# Default initial positions for ur10e's ros2_control fake system

initial_positions:
  ur10_elbow_joint: 0
  ur10_gripper_joint: 0
  ur10_shoulder_lift_joint: 0
  ur10_shoulder_pan_joint: 0
  ur10_wrist_1_joint: 0
  ur10_wrist_2_joint: 0
  ur10_wrist_3_joint: 0
