# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur10e_arm_controller
    - ur10e_gripper_controller

  ur10e_arm_controller:
    type: FollowJointTrajectory
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
  ur10e_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - ur10_gripper_joint