# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur10e_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur10e_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur10e_arm_controller:
  ros__parameters:
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true
ur10e_gripper_controller:
  ros__parameters:
    joints:
      - ur10_gripper_joint
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true